name: trace_pass
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobile_scanner: ^7.1.4
  pdf: ^3.11.3
  printing: ^5.14.2
  http: ^1.6.0
  image_picker: ^1.2.1
  vibration: ^1.9.0
  google_generative_ai: ^0.4.0
  shimmer: ^3.0.0 # Lüks buton parlamaları için ✨
  sqflite: ^2.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # Klasör ismini direkt vererek içindeki tüm PNG'leri tek seferde tanıtıyoruz.
  # Bu yöntem dosya ismi hatalarını (typo) önler.
  assets:
   - assets/images/tarsy/tarsy/